### ISSUE TITLE
Clean master - unit tests fail with panic: runtime error: index out of range

### ISSUE THREAD

**Issue by iplantemn** [ewilde/go-runscope#8]
With a clean, up-to-date master branch, running ```make build``` fails running the unit tests. Stack trace below:

```
go get github.com/golang/lint/golint
go test 
2018/04/30 20:11:56 [DEBUG] reading []bucket 
2018/04/30 20:11:56 [DEBUG] 	request: GET /buckets
2018/04/30 20:11:57 [DEBUG] 	response: 200 {"meta": {"status": "success"}, "data": [{"verify_ssl": true, "trigger_url": "https://api.runscope.com/radar/bucket/a495f288-6680-4f1b-a150-060a9f23c3b1/trigger", "name": "Amused Horse", "key": "7lmk20gi4ip7", "team": {"name": "Someone", "id": "<redacted_team_id>"}, "default": true, "auth_token": null, "tests_url": "https://api.runscope.com/buckets/7lmk20gi4ip7/tests", "collections_url": "https://api.runscope.com/buckets/7lmk20gi4ip7/collections", "messages_url": "https://api.runscope.com/buckets/7lmk20gi4ip7/stream"}], "error": null}
2018/04/30 20:11:57 [DEBUG] creating bucket test
2018/04/30 20:11:57 [DEBUG] 	request: POST /buckets url.Values{"name":[]string{"test"}, "team_uuid":[]string{"<redacted_team_id>"}}
2018/04/30 20:11:57 [DEBUG] &http.Request{Method:"POST", URL:(*url.URL)(0xc42027c080), Proto:"HTTP/1.1", ProtoMajor:1, ProtoMinor:1, Header:http.Header{"Authorization":[]string{"Bearer <redacted_access_token>"}, "Accept":[]string{"application/json"}, "Content-Type":[]string{"application/x-www-form-urlencoded"}}, Body:ioutil.nopCloser{Reader:(*strings.Reader)(0xc42017a480)}, GetBody:(func() (io.ReadCloser, error))(0x1245ec0), ContentLength:56, TransferEncoding:[]string(nil), Close:false, Host:"api.runscope.com", Form:url.Values(nil), PostForm:url.Values(nil), MultipartForm:(*multipart.Form)(nil), Trailer:http.Header(nil), RemoteAddr:"", RequestURI:"", TLS:(*tls.ConnectionState)(nil), Cancel:(<-chan struct {})(nil), Response:(*http.Response)(nil), ctx:context.Context(nil)}
2018/04/30 20:11:57 [DEBUG] 	response: 201 {"meta": {"status": "success"}, "data": {"verify_ssl": true, "trigger_url": "https://api.runscope.com/radar/bucket/d453e86d-b666-4cc5-a735-b36451626ab1/trigger", "name": "test", "key": "swro60ufzjsc", "team": null, "default": false, "auth_token": null, "tests_url": "https://api.runscope.com/buckets/swro60ufzjsc/tests", "collections_url": "https://api.runscope.com/buckets/swro60ufzjsc/collections", "messages_url": "https://api.runscope.com/buckets/swro60ufzjsc/stream"}, "error": null}
2018/04/30 20:11:57 [DEBUG] deleting bucket swro60ufzjsc
2018/04/30 20:11:57 [DEBUG] 	request: DELETE /buckets/swro60ufzjsc
2018/04/30 20:11:57 [DEBUG] 	response: 204
2018/04/30 20:11:57 [DEBUG] creating bucket test-fred
2018/04/30 20:11:57 [DEBUG] 	request: POST /buckets url.Values{"team_uuid":[]string{"<redacted_team_id>"}, "name":[]string{"test-fred"}}
2018/04/30 20:11:57 [DEBUG] &http.Request{Method:"POST", URL:(*url.URL)(0xc420504200), Proto:"HTTP/1.1", ProtoMajor:1, ProtoMinor:1, Header:http.Header{"Authorization":[]string{"Bearer <redacted_access_token>"}, "Accept":[]string{"application/json"}, "Content-Type":[]string{"application/x-www-form-urlencoded"}}, Body:ioutil.nopCloser{Reader:(*strings.Reader)(0xc4201ffa20)}, GetBody:(func() (io.ReadCloser, error))(0x1245ec0), ContentLength:61, TransferEncoding:[]string(nil), Close:false, Host:"api.runscope.com", Form:url.Values(nil), PostForm:url.Values(nil), MultipartForm:(*multipart.Form)(nil), Trailer:http.Header(nil), RemoteAddr:"", RequestURI:"", TLS:(*tls.ConnectionState)(nil), Cancel:(<-chan struct {})(nil), Response:(*http.Response)(nil), ctx:context.Context(nil)}
2018/04/30 20:11:58 [DEBUG] 	response: 201 {"meta": {"status": "success"}, "data": {"verify_ssl": true, "trigger_url": "https://api.runscope.com/radar/bucket/ea8c9e4f-acc2-48e2-b811-082f0e70e141/trigger", "name": "test-fred", "key": "ks1is9a34cdl", "team": null, "default": false, "auth_token": null, "tests_url": "https://api.runscope.com/buckets/ks1is9a34cdl/tests", "collections_url": "https://api.runscope.com/buckets/ks1is9a34cdl/collections", "messages_url": "https://api.runscope.com/buckets/ks1is9a34cdl/stream"}, "error": null}
2018/04/30 20:11:58 [DEBUG] creating bucket test-bob
2018/04/30 20:11:58 [DEBUG] 	request: POST /buckets url.Values{"team_uuid":[]string{"<redacted_team_id>"}, "name":[]string{"test-bob"}}
2018/04/30 20:11:58 [DEBUG] &http.Request{Method:"POST", URL:(*url.URL)(0xc420504400), Proto:"HTTP/1.1", ProtoMajor:1, ProtoMinor:1, Header:http.Header{"Authorization":[]string{"Bearer <redacted_access_token>"}, "Accept":[]string{"application/json"}, "Content-Type":[]string{"application/x-www-form-urlencoded"}}, Body:ioutil.nopCloser{Reader:(*strings.Reader)(0xc4201ffee0)}, GetBody:(func() (io.ReadCloser, error))(0x1245ec0), ContentLength:60, TransferEncoding:[]string(nil), Close:false, Host:"api.runscope.com", Form:url.Values(nil), PostForm:url.Values(nil), MultipartForm:(*multipart.Form)(nil), Trailer:http.Header(nil), RemoteAddr:"", RequestURI:"", TLS:(*tls.ConnectionState)(nil), Cancel:(<-chan struct {})(nil), Response:(*http.Response)(nil), ctx:context.Context(nil)}
2018/04/30 20:11:58 [DEBUG] 	response: 201 {"meta": {"status": "success"}, "data": {"verify_ssl": true, "trigger_url": "https://api.runscope.com/radar/bucket/43d89b97-dc37-4b1d-a537-62a5cd560580/trigger", "name": "test-bob", "key": "jz64w4uirefj", "team": null, "default": false, "auth_token": null, "tests_url": "https://api.runscope.com/buckets/jz64w4uirefj/tests", "collections_url": "https://api.runscope.com/buckets/jz64w4uirefj/collections", "messages_url": "https://api.runscope.com/buckets/jz64w4uirefj/stream"}, "error": null}
2018/04/30 20:11:58 [DEBUG] reading []bucket 
2018/04/30 20:11:58 [DEBUG] 	request: GET /buckets
2018/04/30 20:11:59 [DEBUG] 	response: 200 {"meta": {"status": "success"}, "data": [{"verify_ssl": true, "trigger_url": "https://api.runscope.com/radar/bucket/43d89b97-dc37-4b1d-a537-62a5cd560580/trigger", "name": "test-bob", "key": "jz64w4uirefj", "team": {"name": "Someone", "id": "<redacted_team_id>"}, "default": false, "auth_token": null, "tests_url": "https://api.runscope.com/buckets/jz64w4uirefj/tests", "collections_url": "https://api.runscope.com/buckets/jz64w4uirefj/collections", "messages_url": "https://api.runscope.com/buckets/jz64w4uirefj/stream"}, {"verify_ssl": true, "trigger_url": "https://api.runscope.com/radar/bucket/ea8c9e4f-acc2-48e2-b811-082f0e70e141/trigger", "name": "test-fred", "key": "ks1is9a34cdl", "team": {"name": "Someone", "id": "<redacted_team_id>"}, "default": false, "auth_token": null, "tests_url": "https://api.runscope.com/buckets/ks1is9a34cdl/tests", "collections_url": "https://api.runscope.com/buckets/ks1is9a34cdl/collections", "messages_url": "https://api.runscope.com/buckets/ks1is9a34cdl/stream"}, {"verify_ssl": true, "trigger_url": "https://api.runscope.com/radar/bucket/a495f288-6680-4f1b-a150-060a9f23c3b1/trigger", "name": "Amused Horse", "key": "7lmk20gi4ip7", "team": {"name": "Someone", "id": "<redacted_team_id>"}, "default": true, "auth_token": null, "tests_url": "https://api.runscope.com/buckets/7lmk20gi4ip7/tests", "collections_url": "https://api.runscope.com/buckets/7lmk20gi4ip7/collections", "messages_url": "https://api.runscope.com/buckets/7lmk20gi4ip7/stream"}], "error": null}
2018/04/30 20:11:59 [DEBUG] deleting bucket jz64w4uirefj
2018/04/30 20:11:59 [DEBUG] 	request: DELETE /buckets/jz64w4uirefj
2018/04/30 20:11:59 [DEBUG] 	response: 204
2018/04/30 20:11:59 [DEBUG] reading bucket ks1is9a34cdl
2018/04/30 20:11:59 [DEBUG] 	request: GET /buckets/ks1is9a34cdl
2018/04/30 20:11:59 [DEBUG] 	response: 200 {"meta": {"status": "success"}, "data": {"verify_ssl": true, "trigger_url": "https://api.runscope.com/radar/bucket/ea8c9e4f-acc2-48e2-b811-082f0e70e141/trigger", "name": "test-fred", "key": "ks1is9a34cdl", "team": {"name": "Someone", "id": "<redacted_team_id>"}, "default": false, "auth_token": null, "tests_url": "https://api.runscope.com/buckets/ks1is9a34cdl/tests", "collections_url": "https://api.runscope.com/buckets/ks1is9a34cdl/collections", "messages_url": "https://api.runscope.com/buckets/ks1is9a34cdl/stream"}, "error": null}
2018/04/30 20:11:59 [DEBUG] reading bucket jz64w4uirefj
2018/04/30 20:11:59 [DEBUG] 	request: GET /buckets/jz64w4uirefj
2018/04/30 20:11:59 [DEBUG] 	response: 403 {"meta": {"status": "error"}, "data": {}, "error": {"status": 403, "message": "You must provide a valid Authorization header to use the Runscope API.", "more_info": "https://www.runscope.com/docs/api/authentication"}}
2018/04/30 20:11:59 [DEBUG] deleting bucket jz64w4uirefj
2018/04/30 20:11:59 [DEBUG] 	request: DELETE /buckets/jz64w4uirefj
2018/04/30 20:12:00 [DEBUG] 	response: 403
2018/04/30 20:12:00 [DEBUG] {"meta": {"status": "error"}, "data": {}, "error": {"status": 403, "message": "You must provide a valid Authorization header to use the Runscope API.", "more_info": "https://www.runscope.com/docs/api/authentication"}}
2018/04/30 20:12:00 [DEBUG] deleting bucket ks1is9a34cdl
2018/04/30 20:12:00 [DEBUG] 	request: DELETE /buckets/ks1is9a34cdl
2018/04/30 20:12:00 [DEBUG] 	response: 204
2018/04/30 20:12:00 [DEBUG] creating bucket test
2018/04/30 20:12:00 [DEBUG] 	request: POST /buckets url.Values{"name":[]string{"test"}, "team_uuid":[]string{"<redacted_team_id>"}}
2018/04/30 20:12:00 [DEBUG] &http.Request{Method:"POST", URL:(*url.URL)(0xc420110780), Proto:"HTTP/1.1", ProtoMajor:1, ProtoMinor:1, Header:http.Header{"Authorization":[]string{"Bearer <redacted_access_token>"}, "Accept":[]string{"application/json"}, "Content-Type":[]string{"application/x-www-form-urlencoded"}}, Body:ioutil.nopCloser{Reader:(*strings.Reader)(0xc42017bea0)}, GetBody:(func() (io.ReadCloser, error))(0x1245ec0), ContentLength:56, TransferEncoding:[]string(nil), Close:false, Host:"api.runscope.com", Form:url.Values(nil), PostForm:url.Values(nil), MultipartForm:(*multipart.Form)(nil), Trailer:http.Header(nil), RemoteAddr:"", RequestURI:"", TLS:(*tls.ConnectionState)(nil), Cancel:(<-chan struct {})(nil), Response:(*http.Response)(nil), ctx:context.Context(nil)}
2018/04/30 20:12:00 [DEBUG] 	response: 201 {"meta": {"status": "success"}, "data": {"verify_ssl": true, "trigger_url": "https://api.runscope.com/radar/bucket/8b1dbf32-db8e-4400-84c5-c2dafe06292c/trigger", "name": "test", "key": "uhqsigiuxitj", "team": null, "default": false, "auth_token": null, "tests_url": "https://api.runscope.com/buckets/uhqsigiuxitj/tests", "collections_url": "https://api.runscope.com/buckets/uhqsigiuxitj/collections", "messages_url": "https://api.runscope.com/buckets/uhqsigiuxitj/stream"}, "error": null}
2018/04/30 20:12:00 [DEBUG] creating bucket test2
2018/04/30 20:12:00 [DEBUG] 	request: POST /buckets url.Values{"name":[]string{"test2"}, "team_uuid":[]string{"<redacted_team_id>"}}
2018/04/30 20:12:00 [DEBUG] &http.Request{Method:"POST", URL:(*url.URL)(0xc420106680), Proto:"HTTP/1.1", ProtoMajor:1, ProtoMinor:1, Header:http.Header{"Authorization":[]string{"Bearer <redacted_access_token>"}, "Accept":[]string{"application/json"}, "Content-Type":[]string{"application/x-www-form-urlencoded"}}, Body:ioutil.nopCloser{Reader:(*strings.Reader)(0xc42026dde0)}, GetBody:(func() (io.ReadCloser, error))(0x1245ec0), ContentLength:57, TransferEncoding:[]string(nil), Close:false, Host:"api.runscope.com", Form:url.Values(nil), PostForm:url.Values(nil), MultipartForm:(*multipart.Form)(nil), Trailer:http.Header(nil), RemoteAddr:"", RequestURI:"", TLS:(*tls.ConnectionState)(nil), Cancel:(<-chan struct {})(nil), Response:(*http.Response)(nil), ctx:context.Context(nil)}
2018/04/30 20:12:01 [DEBUG] 	response: 201 {"meta": {"status": "success"}, "data": {"verify_ssl": true, "trigger_url": "https://api.runscope.com/radar/bucket/b3b1aa49-85d2-445e-8a38-2031d00ddc6d/trigger", "name": "test2", "key": "zrgvdb9peb5p", "team": null, "default": false, "auth_token": null, "tests_url": "https://api.runscope.com/buckets/zrgvdb9peb5p/tests", "collections_url": "https://api.runscope.com/buckets/zrgvdb9peb5p/collections", "messages_url": "https://api.runscope.com/buckets/zrgvdb9peb5p/stream"}, "error": null}
2018/04/30 20:12:01 [DEBUG] reading []bucket 
2018/04/30 20:12:01 [DEBUG] 	request: GET /buckets
2018/04/30 20:12:01 [DEBUG] 	response: 200 {"meta": {"status": "success"}, "data": [{"verify_ssl": true, "trigger_url": "https://api.runscope.com/radar/bucket/b3b1aa49-85d2-445e-8a38-2031d00ddc6d/trigger", "name": "test2", "key": "zrgvdb9peb5p", "team": {"name": "Someone", "id": "<redacted_team_id>"}, "default": false, "auth_token": null, "tests_url": "https://api.runscope.com/buckets/zrgvdb9peb5p/tests", "collections_url": "https://api.runscope.com/buckets/zrgvdb9peb5p/collections", "messages_url": "https://api.runscope.com/buckets/zrgvdb9peb5p/stream"}, {"verify_ssl": true, "trigger_url": "https://api.runscope.com/radar/bucket/8b1dbf32-db8e-4400-84c5-c2dafe06292c/trigger", "name": "test", "key": "uhqsigiuxitj", "team": {"name": "Someone", "id": "<redacted_team_id>"}, "default": false, "auth_token": null, "tests_url": "https://api.runscope.com/buckets/uhqsigiuxitj/tests", "collections_url": "https://api.runscope.com/buckets/uhqsigiuxitj/collections", "messages_url": "https://api.runscope.com/buckets/uhqsigiuxitj/stream"}, {"verify_ssl": true, "trigger_url": "https://api.runscope.com/radar/bucket/a495f288-6680-4f1b-a150-060a9f23c3b1/trigger", "name": "Amused Horse", "key": "7lmk20gi4ip7", "team": {"name": "Someone", "id": "<redacted_team_id>"}, "default": true, "auth_token": null, "tests_url": "https://api.runscope.com/buckets/7lmk20gi4ip7/tests", "collections_url": "https://api.runscope.com/buckets/7lmk20gi4ip7/collections", "messages_url": "https://api.runscope.com/buckets/7lmk20gi4ip7/stream"}], "error": null}
2018/04/30 20:12:01 [DEBUG] deleting bucket zrgvdb9peb5p
2018/04/30 20:12:01 [DEBUG] 	request: DELETE /buckets/zrgvdb9peb5p
2018/04/30 20:12:01 [DEBUG] 	response: 204
2018/04/30 20:12:01 [DEBUG] deleting bucket uhqsigiuxitj
2018/04/30 20:12:01 [DEBUG] 	request: DELETE /buckets/uhqsigiuxitj
2018/04/30 20:12:02 [DEBUG] 	response: 204
2018/04/30 20:12:02 [DEBUG] creating bucket terraform-client.go-test
2018/04/30 20:12:02 [DEBUG] 	request: POST /buckets url.Values{"name":[]string{"terraform-client.go-test"}, "team_uuid":[]string{"<redacted_team_id>"}}
2018/04/30 20:12:02 [DEBUG] &http.Request{Method:"POST", URL:(*url.URL)(0xc4203d0280), Proto:"HTTP/1.1", ProtoMajor:1, ProtoMinor:1, Header:http.Header{"Authorization":[]string{"Bearer <redacted_access_token>"}, "Accept":[]string{"application/json"}, "Content-Type":[]string{"application/x-www-form-urlencoded"}}, Body:ioutil.nopCloser{Reader:(*strings.Reader)(0xc4201eba00)}, GetBody:(func() (io.ReadCloser, error))(0x1245ec0), ContentLength:76, TransferEncoding:[]string(nil), Close:false, Host:"api.runscope.com", Form:url.Values(nil), PostForm:url.Values(nil), MultipartForm:(*multipart.Form)(nil), Trailer:http.Header(nil), RemoteAddr:"", RequestURI:"", TLS:(*tls.ConnectionState)(nil), Cancel:(<-chan struct {})(nil), Response:(*http.Response)(nil), ctx:context.Context(nil)}
2018/04/30 20:12:02 [DEBUG] 	response: 201 {"meta": {"status": "success"}, "data": {"verify_ssl": true, "trigger_url": "https://api.runscope.com/radar/bucket/48deb61b-fdd1-4a0a-8333-c79ddc974785/trigger", "name": "terraform-client.go-test", "key": "goy6nm7e3qr5", "team": null, "default": false, "auth_token": null, "tests_url": "https://api.runscope.com/buckets/goy6nm7e3qr5/tests", "collections_url": "https://api.runscope.com/buckets/goy6nm7e3qr5/collections", "messages_url": "https://api.runscope.com/buckets/goy6nm7e3qr5/stream"}, "error": null}
2018/04/30 20:12:02 [DEBUG] reading bucket goy6nm7e3qr5
2018/04/30 20:12:02 [DEBUG] 	request: GET /buckets/goy6nm7e3qr5
2018/04/30 20:12:03 [DEBUG] 	response: 200 {"meta": {"status": "success"}, "data": {"verify_ssl": true, "trigger_url": "https://api.runscope.com/radar/bucket/48deb61b-fdd1-4a0a-8333-c79ddc974785/trigger", "name": "terraform-client.go-test", "key": "goy6nm7e3qr5", "team": {"name": "Someone", "id": "<redacted_team_id>"}, "default": false, "auth_token": null, "tests_url": "https://api.runscope.com/buckets/goy6nm7e3qr5/tests", "collections_url": "https://api.runscope.com/buckets/goy6nm7e3qr5/collections", "messages_url": "https://api.runscope.com/buckets/goy6nm7e3qr5/stream"}, "error": null}
2018/04/30 20:12:03 [DEBUG] deleting bucket goy6nm7e3qr5
2018/04/30 20:12:03 [DEBUG] 	request: DELETE /buckets/goy6nm7e3qr5
2018/04/30 20:12:03 [DEBUG] 	response: 204
2018/04/30 20:12:03 [DEBUG] creating bucket test
2018/04/30 20:12:03 [DEBUG] 	request: POST /buckets url.Values{"name":[]string{"test"}, "team_uuid":[]string{"<redacted_team_id>"}}
2018/04/30 20:12:03 [DEBUG] &http.Request{Method:"POST", URL:(*url.URL)(0xc4203d0880), Proto:"HTTP/1.1", ProtoMajor:1, ProtoMinor:1, Header:http.Header{"Content-Type":[]string{"application/x-www-form-urlencoded"}, "Authorization":[]string{"Bearer <redacted_access_token>"}, "Accept":[]string{"application/json"}}, Body:ioutil.nopCloser{Reader:(*strings.Reader)(0xc42026da00)}, GetBody:(func() (io.ReadCloser, error))(0x1245ec0), ContentLength:56, TransferEncoding:[]string(nil), Close:false, Host:"api.runscope.com", Form:url.Values(nil), PostForm:url.Values(nil), MultipartForm:(*multipart.Form)(nil), Trailer:http.Header(nil), RemoteAddr:"", RequestURI:"", TLS:(*tls.ConnectionState)(nil), Cancel:(<-chan struct {})(nil), Response:(*http.Response)(nil), ctx:context.Context(nil)}
2018/04/30 20:12:03 [DEBUG] 	response: 201 {"meta": {"status": "success"}, "data": {"verify_ssl": true, "trigger_url": "https://api.runscope.com/radar/bucket/bb1dd24d-4aa4-4ecc-8596-0838cde66b23/trigger", "name": "test", "key": "rigqcsj0sesy", "team": null, "default": false, "auth_token": null, "tests_url": "https://api.runscope.com/buckets/rigqcsj0sesy/tests", "collections_url": "https://api.runscope.com/buckets/rigqcsj0sesy/collections", "messages_url": "https://api.runscope.com/buckets/rigqcsj0sesy/stream"}, "error": null}
2018/04/30 20:12:03 [DEBUG] reading integration <redacted_team_id>
2018/04/30 20:12:03 [DEBUG] 	request: GET /teams/<redacted_team_id>/integrations
2018/04/30 20:12:04 [DEBUG] 	response: 404 {"meta": {"status": "error"}, "data": {}, "error": {"error": "Unable to locate integrations list for team '<redacted_team_id>'"}}
2018/04/30 20:12:04 [DEBUG] deleting bucket rigqcsj0sesy
2018/04/30 20:12:04 [DEBUG] 	request: DELETE /buckets/rigqcsj0sesy
2018/04/30 20:12:04 [DEBUG] 	response: 204
--- FAIL: TestCreateSharedEnvironment (0.96s)
	environment_test.go:21: Status: 404 NOT FOUND Error reading integration: <redacted_team_id>
	environment_test.go:25: Expected some integrations to be available found 0 integrations.
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 178 [running]:
testing.tRunner.func1(0xc42052a780)
	/usr/local/go/src/testing/testing.go:742 +0x29d
panic(0x12b5a40, 0x1499220)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/ewilde/go-runscope.TestCreateSharedEnvironment(0xc42052a780)
	/Users/iplante/go/src/github.com/ewilde/go-runscope/environment_test.go:36 +0xa1d
testing.tRunner(0xc42052a780, 0x1323d38)
	/usr/local/go/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:824 +0x2e0
exit status 2
FAIL	github.com/ewilde/go-runscope	7.799s
```

Can you help me fix this issue?
Thanks!
- IP

**Comment by ewilde** [comment]
@iplantemn yep, i think this is because we need at least on [integration](https://www.runscope.com/docs/api/integrations) setup on the account you use to run the tests. 

Because there is no API for creating `integrations` you will need to set one up as a one-off using the runscope UI

Maybe setup a [slack integration](https://www.runscope.com/docs/api-testing/slack) which is what I do
